# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# [START runtime]
runtime: nodejs
env: flex
threadsafe: yes
# [END runtime]

# service: api

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
  - ^node_modules$
  - ^doc$

# [START resources]
resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10
# [END resources]

# [START scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8
# [END scaling]

# [START cloudsql_settings]
#beta_settings:
  # The connection name of your instance on its Overview page in the Google
  # Cloud Platform Console, or use `[YOUR_PROJECT_ID]:[YOUR_REGION]:[YOUR_INSTANCE_NAME]`
#  cloud_sql_instances: "funfunny-2:us-east1:funfunny"
# [END cloudsql_settings]

# [START env]
#env_variables:
#  WEB_INCLUDED: 'false'
# [END env]
